{"cells":[{"cell_type":"markdown","execution_count":null,"metadata":{"tags":[]},"outputs":[],"source":["TSG110 - Azdata returns ApiError\n","================================\n","\n","Description\n","-----------\n","\n","When running `azdata` commands, such as `azdata login`, they fail with\n","the following error:\n","\n","\u003e ERROR: Error processing command: “ApiError” Internal Server Error\n","\n","### Steps\n","\n","This has been seen to be caused by an issue with the `controller`. The\n","next steps to perform is to analyze the controller logs. Use the TSG(s)\n","listed below to do this."]},{"cell_type":"markdown","execution_count":null,"metadata":{"tags":[]},"outputs":[],"source":["Related\n","-------\n","\n","- [TSG036 - Controller logs](../log-analyzers/tsg036-get-controller-logs.ipynb)\n"]}],"nbformat":4,"nbformat_minor":5,"metadata":{"kernelspec":{"name":"python3","display_name":"Python 3"},"pansop":{"related":"TSG036","test":{"strategy":"","types":null,"disable":{"reason":"","workitems":null,"types":null}},"target":{"current":"","final":""},"internal":{"parameters":null,"symlink":false},"timeout":"0"},"language_info":{"codemirror_mode":"{ Name: \"\", Version: \"\"}","file_extension":"","mimetype":"","name":"","nbconvert_exporter":"","pygments_lexer":"","version":""},"widgets":[]}}